# Generated by Django 6.0 on 2026-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phase', models.CharField(choices=[('P1', 'Phase 1'), ('P2', 'Phase 2')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
