# Generated by Django 6.0 on 2026-01-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='phase',
            field=models.CharField(choices=[('P1', 'Phase 1'), ('P2', 'Phase 2')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('MAINT', 'Maintenance'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20),
        ),
    ]
