# Generated by Django 6.0 on 2026-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_contactinfo_name_contactinfo_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='site',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.AddField(
            model_name='site',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
