# Generated by Django 6.0 on 2026-01-28 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_site_is_active_remove_site_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_status', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sites.site')),
            ],
        ),
    ]
