# Generated by Django 6.0 on 2026-01-28 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_sitestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatushistory',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
